FROM registry.cn-shenzhen.aliyuncs.com/tsinghua_gd/tts:V1.5
LABEL maintainer Jerik "carter7777@qq.com"

RUN pip3 --no-cache-dir install \
		keras \
		torch \
		webrtcvad 


# RUN git clone https://github.com/Rayhane-mamah/Tacotron-2.git
# WORKDIR Tacotron-2