FROM registry.cn-shenzhen.aliyuncs.com/jerik/tacotron:v5
LABEL maintainer Jerik "carter7777@qq.com"

RUN pip3 --no-cache-dir install \
		torch==1.7.0

RUN pip --no-cache-dir install \
  phonemizer \
  epitran \
  fastdtw \
  pinyin \
  seaborn \
  romkan \
  mecab-python3 \
  unidic-lite \
  pykakasi \
  phkit \
  aukit \
  pyworld

RUN apt-get update && apt-get install -y festival espeak-ng mbrola
RUN pip --no-cache-dir install \
  librosa==0.7.0 \
  websocket==0.2.1 \
  websocket-client==0.56.0 \
  pymysql \
  redis \
  enchant \
  langid \
  num2words \
  sqlalchemy \
  mysql-connector \
  tqdm==4.56.0 
RUN rm -rf /var/lib/apt/lists/*

# 解决时区问题
ENV TZ "Asia/Shanghai"	
