FROM registry.cn-shenzhen.aliyuncs.com/tsinghua_gd/tts:V1.5
LABEL maintainer Jerik "carter7777@qq.com"

RUN pip3 --no-cache-dir install \
		keras \
		torch==1.3.1 \
		webrtcvad 

RUN apt-get update

RUN apt-get install -y libespeak-dev

RUN pip3 install \
    aeneas \
    pydub \
    jieba

# RUN git clone https://github.com/Rayhane-mamah/Tacotron-2.git
# WORKDIR Tacotron-2
