FROM registry.cn-shenzhen.aliyuncs.com/tsinghua_gd/tts:V1.5
LABEL maintainer Jerik "carter7777@qq.com"

RUN pip3 --no-cache-dir install \
		keras==2.3.1 \
		torch==1.3.1 \
		webrtcvad==2.0.10

RUN apt-get update

RUN apt-get install -y libespeak-dev ffmpeg

RUN pip3 install \
    aeneas \
    pydub \
    jieba \
    recognizers-text-suite \
    spacy==2.2.0 \
    neuralcoref \
    textacy    

# RUN 
# WORKDIR 
