FROM registry.cn-shenzhen.aliyuncs.com/jerik/tacotron:v2
LABEL maintainer Jerik "carter7777@qq.com"



RUN pip3 --no-cache-dir install \
	pandas==0.24.2 \
	xlrd==1.2.0 \
	numba==0.48.0 \
	openpyxl \
	xlwt \
	umap-learn \
	Pillow \
	opencv-python \
	scikit-image

RUN pip --no-cache-dir install \
        jupyter_contrib_nbextensions
		
RUN mkdir nohup
RUN jupyter notebook --generate-config			
RUN jupyter contrib nbextension install --user
RUN jupyter nbextension enable codefolding/main

ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV TERM screen

 
