FROM registry.cn-shenzhen.aliyuncs.com/tsinghua_gd/tts:V1.5
LABEL maintainer Jerik "carter7777@qq.com"

RUN pip3 --no-cache-dir install \
		keras==2.3.1 \
		torch==1.3.1 \
		webrtcvad==2.0.10

RUN apt-get update

RUN apt-get install -y libespeak-dev ffmpeg

RUN pip3 install \
    aeneas \
    pydub \
    jieba \
    recognizers-text-suite \
    spacy==2.2.0 \
    neuralcoref \
    textacy    \
	pandas==0.24.2 \
	xlrd==1.2.0 \
	numba==0.48.0 \
	openpyxl

RUN pip --no-cache-dir install \
        jupyter_contrib_nbextensions
		
RUN jupyter contrib nbextension install --user
RUN jupyter nbextension enable codefolding/main

ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV TERM screen

RUN mkdir nohup
RUN jupyter notebook --generate-config	 