
FROM registry.cn-shenzhen.aliyuncs.com/jerikye/tacotron:v1
LABEL maintainer Jerik "carter7777@qq.com"

RUN pip3 --no-cache-dir install \
		spacy

RUN python -m spacy download en_core_web_sm

pip pip3 --no-cache-dir install \
    neuralcoref \
    textacy
