FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04
LABEL maintainer Jerik "carter7777@qq.com"

# Install dependencies
RUN apt-get -y update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        python3-dev \
        python3-pip \
        git \
        g++ \
        make \
        wget \
        unzip \
        vim \
        build-essential \
        libssl-dev \
        libffi-dev \
        libxml2 \
        libxml2-dev \
        libxslt1-dev \
        libsndfile1 \
        libasound-dev \
        portaudio19-dev \
        libportaudio2 \
        libportaudiocpp0  \
        libespeak-dev \
		ffmpeg		
    

# pip 升级
RUN python3 -m pip install --upgrade pip

# 安装基础库
RUN pip install -U setuptools
RUN pip --no-cache-dir install \
        numpy==1.16.4 \
        pandas==0.24.2 \
        scipy==1.2.1 \
        scikit-learn \
        tqdm \
        matplotlib \
        jupyterlab \
        librosa==0.7.0 \
        Unidecode 
	  
	  
RUN pip --no-cache-dir install \
        jieba \
        pypinyin \
        pydub \
        sounddevice \
		pyaudio \
        falcon \
        inflect \
        aeneas \
        recognizers-text-suite \
        spacy==2.2.0 \
        neuralcoref \
        textacy \
		xlrd==1.2.0 \
		numba==0.48.0 \
		openpyxl

RUN pip --no-cache-dir install \
		tensorflow-gpu==1.15.0\
		keras==2.3.1 \
		torch==1.6.0 \
		webrtcvad==2.0.10

# 安装服务常用包
RUN pip --no-cache-dir install \
        flask \
        flask-restful \
        flask_jsonrpc \
        fire \
        requests_toolbelt
		
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV TERM screen

# 删除 apt lists
# RUN rm -rf /var/lib/apt/lists/*

# 终端设置
# 默认值是dumb，这时在终端操作时可能会出现：terminal is not fully functional
ENV TERM xterm

# 解决时区问题
ENV TZ "Asia/Shanghai"	  

RUN mkdir nohup
RUN jupyter notebook --generate-config	  
