From registry.cn-shenzhen.aliyuncs.com/dgx_a100/tts:v1
LABEL maintainer Jerik "carter7777@qq.com"

RUN pip --no-cache-dir install \
	jupyterlab \
  jupyter_contrib_nbextensions \
	pysrt \
  librosa==0.7.0 \
  websocket==0.2.1 \
  websocket-client==0.56.0 \
  fastapi \
  minio \
  uvicorn 

RUN pip --no-cache-dir install \
  keras==2.3.1 \
  phonemizer \
  epitran \
  fastdtw \
  pinyin \
  seaborn \
  romkan \
  mecab-python3 \
  unidic-lite \
  pykakasi \
  phkit \
  aukit \
  pyworld
  
RUN pip --no-cache-dir install \  
  pymysql \
  redis \
  langid \
  num2words \
  enchant
  
# RUN pip --no-cache-dir install \  
#  pandas==0.24.2 \
#  umap-learn \
#  Pillow \
#  opencv-python \
#  scikit-image \
#  numba==0.48.0 \
#  openpyxl \
#  xlwt \
#  xlrd \  
#  xlrd
  
# 删除 apt lists
# RUN rm -rf /var/lib/apt/lists/*

# 终端设置
# 默认值是dumb，这时在终端操作时可能会出现：terminal is not fully functional
ENV TERM xterm

# 解决时区问题
ENV TZ "Asia/Shanghai"	  		
		
		
RUN mkdir nohup
RUN jupyter notebook --generate-config			
RUN jupyter contrib nbextension install --user
RUN jupyter nbextension enable codefolding/main
