
From registry.cn-shenzhen.aliyuncs.com/jerik/tts:a100_20210319
LABEL maintainer Jerik "carter7777@qq.com"

  
RUN pip --no-cache-dir install \
	matplotlib \
	numpy==1.16.2 \
	inflect==0.2.5 \
	librosa==0.6.0 \
	scipy==1.0.0 \
	tensorboardX==1.1 \
	Unidecode==1.0.22 \
	pillow
	
RUN rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/NVIDIA/apex
WORKDIR /apex/ 
RUN pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
